Automatic: Automatisch
FooterText: Gemacht mit Kaffee und Haskell.
JumpToContent: Springe zum Inhalt…
PageBlog: Blog
PageChat: Chat
PageHome: Homepage
PageSubtitle: Waschbären? Im Internet? Das ist wahrscheinlicher als es klingt!
PageTitle: Lottes Dachboden
SettingDarkTheme: Dunkler Stil
SettingLanguage: Sprache:
SettingLightTheme: Heller Stil
SettingsCookieNotice: Wir benutzen Cookies, um veränderte Einstellungen zu speichern und an dem Server zu senden.
SettingsMenu: Einstellungen
SettingTheme: Stil: