AlternateLink: (Alt.)
Automatic: Automatisch
Github: Github
GPGKeyNote: (GPG Schlüssel)
FooterText: Gemacht mit Kaffee und Haskell.
FootnoteBridgedMatrix: Mit Matrix verbunden.
ImgVintagecoyotePrideicon: Portrait von Charlotte, ein orangener Waschbär mit rosa Gesicht und lilafarbener Maske. Es lächelt und trägt einen Schal, der mit den Farben der Asexuellen-Pride-Flagge ausgestattet, nämlich schwarz, grau, weiß, und lila. Im hintergrund ist die Therian-Pride-Flagge, welches die Farben grün, weiß, und lila hat, und ein komplexes Symbol mit einem Dreieck, einem Kreis, und einem Heptagramm besteht.
ImgVintagecoyotePrideiconFigcaption: Illustration von <a href="https://nitter.net/vintagecoyote" lang="en">yote</a>
JumpToContent: Springe zum Inhalt…
MyDiscord: Discord (darkkirb)
MyEmail: E-Mail (lotte@chir.rs)
MyFediverse: Fediversum (@charlotte@akko.chir.rs)
MyForgejo: Mein Forgejo Server
MyKeybase: Keybase (darkkirb)
MyMatrixChat: Matrix (@lotte:chir.rs)
MySignalWhatsapp: Signal/Whatsapp: verfügbar auf nachfrage
MyTelegram: Telegram (darkkirb)
PageBlog: Blog
PageChat: Chat
PageHome: Homepage
PageSubtitle: Waschbären? Im Internet? Das ist wahrscheinlicher als es klingt!
PageTitle: Lottes Dachboden
Peertube: Peertube
ReportedSightings: Gemeldete Sichtungen
ReportedSightingsSubtitle: Sortiert nach Meldungsseriösität.
SelfIntroPart1: Hi! Ich bin <span class="p-name">Charlotte</span>, oder auch nur <span class="p-nick">Lotte</span>, eine <abbr class="dt-bday" title="2001-01-10">22 Jahre alte</abbr> Waschbärin-Therian und <span class="p-role">Studentin</span> aus <span class="p-country-name">Deutschland</span>.
SelfIntroPart2: Ich bin Systemadministratorin, Softwareentwicklerin, und manchmal Hardwaredesignerin.
SelfIntroPart3: Ich liebe Kaffe, Lasagne, Pizza, Waschbären, und Plüschtiere.
SelfIntroPart4: Meine Pronomen sind <span class="u-pronoun">es</span> und <span class="u-pronoun">sie</span>.
SettingDarkTheme: Dunkler Stil
SettingLanguage: Sprache:
SettingLightTheme: Heller Stil
SettingsCookieNotice: Wir benutzen Cookies, um veränderte Einstellungen zu speichern und an dem Server zu senden.
SettingsMenu: Einstellungen
SettingTheme: Stil: