Akkoma: Akkoma
AlternateLink: (alt)
AndALotMore: and a lot more…
Authorize: Authorize
Automatic: Automatic
Forgejo: Forgejo
Github: Github
GPGKeyNote: (GPG Key)
FooterText: Made with coffee in Haskell.
FootnoteBridgedMatrix: Bridged to Matrix.
ImgVintagecoyotePrideicon: Portrait of Charlotte, an orange raccoon with pink face and purple mask. It is smiling and wearing a scarf colored asexual pride flag colors, black, gray, white, and purple. In the background there’s a therian pride flag, which is green, white, and purple, and has a complex symbol consisting of a triangle, circle, and a heptagram.
ImgVintagecoyotePrideiconFigcaption: Artwork by <a href="https://nitter.net/vintagecoyote" lang="en">yote</a>
JumpToContent: Jump to content…
MyDiscord: Discord (darkkirb)
MyEmail: Email (lotte@chir.rs)
MyFediverse: Fediverse (@charlotte@akko.chir.rs)
MyForgejo: My Forgejo instance
MyKeybase: Keybase (darkkirb)
MyMatrixChat: Matrix (@lotte:chir.rs)
MySignalWhatsapp: Signal/Whatsapp: available upon request
MyTelegram: Telegram (darkkirb)
Nextcloud: Nextcloud
PageBlog: Blog
PageChat: Chat
PageHome: Homepage
PageSubtitle: Raccoons? On the internet? It’s more likely than you think!
PageTitle: Lotte’s Attic
Peertube: Peertube
ReportedSightings: Reported Sightings
ReportedSightingsSubtitle: Ordered by report credibility.
SiteIndex: Index
SelfIntroPart1: Hi! I’m <span class="p-name">Charlotte</span>, or just <span class="p-nick">Lotte</span>, a <abbr class="dt-bday" title="2001-01-10">22 year old</abbr> <span class="p-species">raccoon</span> therian and <span class="p-role">student</span> from <span class="p-country-name">Germany</span>.
SelfIntroPart2: I do system administration, software development, and occasionally hardware design.
SelfIntroPart3: I love coffee, lasagna, pizza, raccoons, and plushies.
SelfIntroPart4: My pronouns are <span class="u-pronoun">it/its</span>, <span class="u-pronoun">rac/racs/racself</span>, <span class="u-pronoun">🦝/🦝s/🦝self</span>, and <span class="u-pronoun">plush/plushs/plushself</span>.
SettingDarkTheme: Dark theme
SettingLanguage: Language:
SettingLightTheme: Light theme
SettingsCookieNotice: We use cookies to store and transmit changed settings.
SettingsMenu: Settings
SettingTheme: Theme:
Username: Username: