Automatic: Automatique
FooterText: Fait en Haskell avec du café
JumpToContent: Vers le contenu
PageBlog: Blogue
PageChat: Tchat
PageHome: Page principale
PageSubtitle: Ratons laveurs? Sur l'internet? On ne sait jamais...
PageTitle: Le grenier de Lotte
SettingDarkTheme: Theme nuit
SettingLanguage: Language:
SettingLightTheme: Theme clair
SettingsCookieNotice: Nous utilisont des Cookies pour transmettre et enregistrer les préférences d'utilisateur
SettingsMenu: Preferences
SettingTheme: Theme: