Automatic: zmiku
FooterText: ti zbasu sepi'o le tcafi .e la .xaskal.
JumpToContent: .e'o klama le se tcido
PageBlog: le snukarni
PageChat: lai casnu
PageHome: le ralju kibystu
PageSubtitle: ianai le .arxokuna cu pilno le mujysamseltcana .i le du'u le go'i cu jetnu cu zmadu le du'u do krici le go'i vau le lakne 
PageTitle: le zdaga'u pe la .tcarLOT.
SettingDarkTheme: le manku staile
SettingLanguage: le bangu cu
SettingLightTheme: le blabi staile
SettingsCookieNotice: fau le nu do galfi le gaftercu'a kei mi morji le go'i sepi'o le skami pe do
SettingsMenu: le gaftercu'a
SettingTheme: le staile cu