Akkoma:  
AlternateLink:          
AndALotMore:      
Authorize:  
Automatic:  (zmiku)
Forgejo: _{MyForgejo}
Github:          
GPGKeyNote:       GPG
FooterText:        
FootnoteBridgedMatrix:   
ImgVintagecoyotePrideicon:                                                                                      
ImgVintagecoyotePrideiconFigcaption:  <a href="https://nitter.net/vintagecoyote" lang="en"></a>     
JumpToContent:     
MyDiscord:     darkkirb   
MyEmail:  lotte@chir.rs     
MyFediverse:  lotte@chir.rs     
MyForgejo:  
MyKeybase:     darkkirb   
MyMatrixChat:     darkkirb   
MySignalWhatsapp:                    
MyTelegram:    darkkirb   
Nextcloud:  
PageBlog:  
PageChat:  
PageHome:   
PageSubtitle:                         
PageTitle:     
Peertube:  
ReportedSightings:       
ReportedSightingsSubtitle:         
SiteIndex:  
SelfIntroPart1:     <span class="p-name"></span>      <abbr class="dt-bday" title="2001-01-10"></abbr>  <abbr title="                                  Therian      "></abbr>  <span class="p-species"></span>  <span class="p-role"></span>   <span class="p-country-name"> </span>
SelfIntroPart2:            
SelfIntroPart3:                    
# Originally this listed the pronouns, which aren’t relevant in lojban
SelfIntroPart4:        
SettingDarkTheme:    (le manku staile)
SettingLanguage:    
SettingLightTheme:    (le blabi staile)
SettingsCookieNotice:                  
SettingsMenu:   (le gaftercu'a)
SettingTheme:    
Username:      