Automatic: Automatisch
FooterText: Gemaakt met koffie in Haskell
JumpToContent: Direct naar inhoud
PageBlog: Blog
PageChat: Chat
PageHome: Homepage
PageSubtitle: Wasberen? Op het internet? Je zou het bijna niet geloven
PageTitle: Lotte’s Zolder
SettingDarkTheme: Donker thema 
SettingLanguage: Taal:
SettingLightTheme: Licht thema
SettingsCookieNotice: Wij gebruiken cookies om gebruikersinstellingen bij te houden
SettingsMenu: Instellingen
SettingTheme: Thema: