Automatic: anu tan ilo
JumpToContent: o tawa e lipu
PageBlog: lipu mute
PageChat: tomo toki
PageHome: lipu suli
PageSubtitle: kijetesantakalu li kepeken ala kepeken e linja kulupu? toki insa sina li toki ni: ni li ala. taso ni mute.
PageTitle: tomo sewi pi kije Lote
SettingDarkTheme: lukin mun
SettingLanguage: toki li
SettingLightTheme: lukin suno
SettingsCookieNotice: mi pana e lipu lili tawa ilo nanpa sina tan ni: sina ante e lawa.
SettingsMenu: lawa ante
SettingTheme: lukin li