Akkoma: 󱤟󿫅󱦐󱦔󱤅󱦒󱤘󱦒󱥺󱦒󱤺󱦒󱤇󱦒󱦑
AlternateLink: (󱤇)
AndALotMore: 󱤼󱥹
Automatic: 󱤇󱥧󱤎 (anu tan ilo)
Forgejo: _{MyForgejo}
Github: 󱤴󱥉󱤉󱤤󿪏󿦄󱦔󿩣󱥁󱦔󱥹
GPGKeyNote: (󱤎󱤈)
FooterText:󱤴󱥉󱤉󱥁󿩞󱥪󱦔󱦓󱦔󱤢󱦔󱤂󱦔,󿩞󱥬󱦔󱤎󱦔󱦐󱦔󱤈󱦒󱥦󱦒󱥰󱦒󱤘󱦒󱤋󱦒󱤣󱦒󱥰󱦒󱦑
FootnoteBridgedMatrix: 󱤴󱤙󱤉󱥁󿩞󿦈󱦔󱦐󱦔󱤺󱦒󱤅󱦒󱥨󱦒󱥅󱦒󱤬󱦒󱤌󱦒󱦑
ImgVintagecoyotePrideicon: 󱥁󱤧󱥠󱤉󿪘󱦐󱦔󱤫󱦒󱥅󱦒󱥭󱦒󱤋󱦒󱦑.󱥆󱤧󿯅.󱥟󱥆󱤧󱤫󱥦.󱤥󱦓󱥟󱦔󱥆󱦔󱤧󱤫󱥣.󱥆󱤧󿨈,󱤧󱤥󱤉󱤥󱤩.󱥁󱤥󱤧󱤞󱥖󱤥󱥣󱤞󱦓󱥯󱦔󱤂󱦔.󱤸󱦀󱤧󱤬󱤉󱤥󱥣󱤞󱥩󱥁:󱥢󱤧󱤮󱥖󱤉󱤑
ImgVintagecoyotePrideiconFigcaption: <a href="https://nitter.net/vintagecoyote" lang="en">󿪈󱦐󱦔󱤓󱦒󱥺󱦒󱥪󱦒󱤋󱦒󱦑</a>󱤧󱥉󱤉󱥠󱥁
JumpToContent: 󱥄󱥩󱤉󱤪
MyDiscord: 󿦈󱦐󱥝󱦒󱤌󱦒󱤜󱦒󱥆󱦒󱦑󱤡,󱥂󱤴󱤧 darkkirb.
MyEmail: 󱥞󱤘󱥌󱤉󱥠󱥩lotte@chir.rs
MyFediverse: 󱤟󿫄󱤡,󱥂󱤴󱤡@charlotte@akko.chir.rs
MyForgejo: 󱤴󱥉󱤉󱤤󿪏󿦄󱦔󿩣󱥁󱦔.
MyKeybase: 󱤟󱦓󱤎󱦔󱤈󱦔󱤡,󱥂󱤴󱤧 darkkirb.
MyMatrixChat: 󱥞󱥷󱥬󿪏󱤴󱦔󱤡,󱥂󱤴󱤧@lotte:chir.rs󿩣󿦈󱦔󱦐󱦔󱤺󱦒󱤅󱦒󱥨󱦒󱥅󱦒󱤬󱦒󱤌󱦒󱦑
MySignalWhatsapp: 󱥞󱥷󱤉󱤽󱦓󿦄󱦔󱥧󱤴󱤡,󱥄󱥬󱤉󱤴
MyTelegram: 󿦈󱦐󱥪󱦒󱤋󱦒󱤬󱦒󱤋󱦒󱤖󱦒󱤈󱦒󱦑󱤡,󱥂󱤴󱤧 darkkirb.
Nextcloud: 󱥓󱤪󱦓󿦄󱦔.
PageBlog: 󱤪󱤼
PageChat: 󱥭󱥬
PageHome: 󱤪󱥣
PageSubtitle: 󱦀󱤧󱤙󱦔󿩕󱤙󱦔󱤉󿫄? 󱥬󱤏󱥞󱤧󱥬󱤉󱥁:󱥁󱤧󱤂.󱥨󱥁󱤼.
PageTitle: 󱥭󱦖󱥚󱦓󱦀󱦔󱦐󱦔󱤫󱥅󱥭󱤋󱦑
Peertube: 󱤪󱦓󿨛󱦔.
ReportedSightings: 󱤑󱤧󱤮󱤉󿪹󿪺󿪺󿪻󱤬󱥁
ReportedSightingsSubtitle: 󱤿󿪤󱤧󱤬,󱤿󱤅󱤧󱦣󱦔󿩕󱦣󱦔.
SiteIndex: 󱤿󱤪
SelfIntroPart1: 󱥬󱤀! 󱤴<span class="p-name">󿪘󱦐󱦔󱤫󱦒󱥅󱦒󱥭󱦒󱤋󱦒󱦑</span>. 󱤱󱤧󱤱󱤉󱤴<abbr class="dt-bday" title="2001-01-10">󱤸󱥜󱥣󱦓󿫫󱦔󿫧󱦔</abbr>. 󱤴<span class="p-species">󱦀</span>. 󱤴<span class="p-role">󱤖󱥡</span>. 󱤴󱤬󱤉<span class="p-country-name">󱤰󱦐󱥭󱦒󱥺󱦒󱥝󱦒󱤏󱦒󱦑</span>.
SelfIntroPart2: 󱤴󱤤󱤉󿦄, 󱤴󱥬󿪏󱥆󱦔,󱤴󱤱󱤉󱥆.
SelfIntroPart3: 󱤴󱥅󱤉󱥪󱦓󱤢󱦔󱤂󱦔, 󱤉󱤶, 󱤉󿫈, 󱤉󿪹󿪺󿪺󿪻, 󱤉󱤻󱥢󿬼.
# Originally about pronouns, so I made it about head nouns instead
SelfIntroPart4: 󱥂󱥟󱤴󱤧󱦀. 󱤇󿩞󱥠󱦔󱦐󱦔󱤪󱦒󱤅󱦒󱥜󱦒󱤎󱦒󱥃󱦒󱤇󱦒󱦑󱤡, 󱥆󱤧󱦐󱤚󱦒󱤎󱦒󱤒󱦒󱤋󱦒󱦑.
SettingDarkTheme: 󱤮󱤺 (lukin mun)
SettingLanguage: 󱥬󱤧
SettingLightTheme: 󱤮󱥤 (lukin suno)
SettingsCookieNotice: 󱤴󱥌󱤉󱤪󱤨󿪏󿦄󱦔󱥞󱥧󱥁: 󱥞󱤆󱤉󱤤.
SettingsMenu: 󱤤󱤆 (lawa ante)
SettingTheme: 󱤮󱤧