[package]
name = "chir-rs-auth"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
diesel = { version = "2.0.2", features = [
    "postgres",
    "time",
    "serde_json",
    "chrono",
] }
dotenvy = "0.15.6"
educe = "0.4.20"
